apiVersion: v1
kind: Pod
metadata:
    name: app
    labels: 
      app: nginx
      environment: development
spec:
   containers:
   - name: nginx-controller
     image: nginx
     ports:
     - containerPort: 8080
   - name: sidecar-container
     image: busybox
     args: #["sleep", "3600" ] Can be written lists like this as well
      - "sleep"
      - "3600"
     ports:
     - containerPort: 5000
      