apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 5678
        args:
        - "-text=Hello from Vinay Ellulla"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 5678
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}
