apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  annotations:
    kubernetes.io/change-cause: "Intial release with nginx:1.19" 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        environment: development
    spec:
      containers:
        - image: nginx:1.19
          name: nginx-container