apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc 

spec:
  replicas: 3
  selector: 
    name: nginx
    environment: dev
  template:
    metadata:
      labels:
        name: nginx
        environment: dev 
    spec:
      containers:
        - name: nginx-container
          image: nginx 
