#Stage 1 build stage
FROM python:3.9-slim as build
WORKDIR /app
COPY app.py .
RUN pip install flask && apt update && apt install -y build-essential


#stage 2 final/production

FROM python:3.9-slim
WORKDIR /app
COPY --from=build /app .
RUN pip install flask
EXPOSE 5000
ENTRYPOINT [ "python" ]
CMD [ "app.py" ]