apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      tolerations: 
        - key: "storage"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "env"
          operator: "Equal"
          value: "prod"
          effect: "NoSchedule"
      containers:
      - name: nginx
        image: nginx

# --- 
# apiVersion: v1
# kind: Pod
# metadata:
#   name: myapp2
#   labels:
#     app.kubernetes.io/name: myapp
# spec:
#   containers:
#   - name: nginx
#     image: nginx 
#   tolerations:
#     - key: "storage"
#       operator: "Exists" 
#       effect: "NoSchedule"
